config/routes.rb
Rails.application.routes.draw do
  get '/version', to: 'events#getVersion'
  resources :faqs
  resources :places

  
  resources :multimedia_types
  resources :people
  resources :profiles
  resources :events
  resources :events do
    resources :places
    resources :activities
    resources :event_dates
    resources :people
    resources :information
    resources :multimedia
  end
  resources :companies
  namespace :api do
    namespace :v1 do
      resources :faqs
      resources :places

      
      resources :multimedia_types
      # resources :people
      resources :profiles
      resources :events
      resources :companies
      resources :events do
        resources :places
        resources :event_dates
        resources :activities
        resources :people
        resources :information
        resources :multimedia
        post '/message', to: 'events#postMessage'
      end
      post '/friendships', to: 'people#addFriend', as: 'new_friendship'
      get '/friendships/:id', to: 'people#getFriends'
      
    end
  end
  root to: "events#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activities_person.rb
class ActivitiesPerson < ApplicationRecord
  belongs_to :activity
  belongs_to :person
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :event_date
  belongs_to :places_event
  has_many :activities_people, dependent: :destroy
  has_many :people, through: :activities_people
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :person
  belongs_to :event_date
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :persons
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :persons_events, -> { where profile_id: 2 }
  has_many :people, -> { order(:name) }, through: :persons_events
  has_many :profiles, through: :persons_events
  has_many :multimedia
  has_many :information
  has_many :event_dates, -> { order(:date) }
  has_many :faqs
  has_many :places_events
  has_many :places, through: :places_events
  has_many :activities, through: :places_events
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  belongs_to :event
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :person, :foreign_key => :friend1
    belongs_to :person, :foreign_key => :friend2
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :event
end

app/models/multimedia_type.rb
class MultimediaType < ApplicationRecord
  has_many :multimedia
end

app/models/multimedium.rb
class Multimedium < ApplicationRecord
  belongs_to :multimedia_type
  belongs_to :event
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :company, optional: true
  has_many :persons_events, dependent: :destroy
  has_many :events, through: :persons_events
  has_many :profiles, through: :persons_events
  has_many :activities_people, dependent: :destroy
  has_many :activities, through: :activities_people
  has_many :friendships ,:foreign_key => :friend1
  has_many :friends, through: :friendships,source: :person
end

app/models/persons_event.rb
class PersonsEvent < ApplicationRecord
  belongs_to :person
  belongs_to :event
  # belongs_to :profile
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :places_events
  has_many :events, through: :places_events
  has_many :activities, through: :places_events
end

app/models/places_event.rb
class PlacesEvent < ApplicationRecord
  belongs_to :place
  belongs_to :event
  has_many :activities
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :persons_events
  has_many :events, through: :persons_events
  has_many :people, through: :persons_events
end

app/controllers/api/v1/faqs_controller.rb
class Api::V1::FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :update, :destroy]

  # GET /faqs
  def index
    @faqs = Faq.all

    render json: @faqs
  end

  # GET /faqs/1
  def show
    render json: @faq
  end

  # POST /faqs
  def create
    @faq = Faq.new(faq_params)

    if @faq.save
      render json: @faq, status: :created, location: @faq
    else
      render json: @faq.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /faqs/1
  def update
    if @faq.update(faq_params)
      render json: @faq
    else
      render json: @faq.errors, status: :unprocessable_entity
    end
  end

  # DELETE /faqs/1
  def destroy
    @faq.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/faqs/_form.html.erb
<%= form_with(model: faq, local: true) do |form| %>
  <% if faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_area :question %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_area :answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faqs</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faqs.each do |faq| %>
      <tr>
        <td><%= faq.question %></td>
        <td><%= faq.answer %></td>
        <td><%= link_to 'Show', faq %></td>
        <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
        <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faq', new_faq_path %>

app/views/faqs/new.html.erb
<h1>New Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>