config/routes.rb
Rails.application.routes.draw do
  get '/version', to: 'events#getVersion'
  resources :faqs
  resources :places

  
  resources :multimedia_types
  resources :people
  resources :profiles
  resources :events
  resources :events do
    resources :places
    resources :activities
    resources :event_dates
    resources :people
    resources :information
    resources :multimedia
  end
  resources :companies
  namespace :api do
    namespace :v1 do
      resources :faqs
      resources :places

      
      resources :multimedia_types
      # resources :people
      resources :profiles
      resources :events
      resources :companies
      resources :events do
        resources :places
        resources :event_dates
        resources :activities
        resources :people
        resources :information
        resources :multimedia
        post '/message', to: 'events#postMessage'
      end
      post '/friendships', to: 'people#addFriend', as: 'new_friendship'
      get '/friendships/:id', to: 'people#getFriends'
      
    end
  end
  root to: "events#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :company, optional: true
  has_many :persons_events, dependent: :destroy
  has_many :events, through: :persons_events
  has_many :profiles, through: :persons_events
  has_many :activities_people, dependent: :destroy
  has_many :activities, through: :activities_people
  has_many :friendships ,:foreign_key => :friend1
  has_many :friends, through: :friendships,source: :person
end

app/controllers/api/v1/people_controller.rb
class Api::V1::PeopleController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :addFriend]
  before_action :set_person, only: [:show, :update, :destroy]
  before_action :set_event
  # GET /people
  def index
    if @event != nil
      @people = @event.people.all
    else
      @people = Person.all
    end

    render json: @people, include: { :company => { :only => :name } }
  end

  # GET /people/1
  def show
    render json: @person
  end

  # POST /people
  def create
    # render plain: person_params[:company_name], status: :created
    @person = Person.new
    company_id = person_params[:company_id]
    if company_id < 1
      company = Company.new
      company.name = person_params[:company_name]
      company.save()
      company_id = company.id
    end
    @person.name = person_params[:name]
    @person.email = person_params[:email]
    @person.company_id = company_id
    @person.phone = person_params[:phone]
    PersonsEvent.create(profile_id: 1, person: @person, event: @event)
    if @person.save
      render json: @person, status: :created, location: @person
    else
      render json: @person.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      render json: @person
    else
      render json: @person.errors, status: :unprocessable_entity
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
  end

  def addFriend
    if Friendship.where(friend1: params[:friend1_id], friend2: params[:friend2_id]).empty?
      
      if Friendship.where(friend2: params[:friend1_id], friend1: params[:friend2_id]).empty?
        render json: Friendship.create(friend1: params[:friend1_id], friend2: params[:friend2_id])
        return 
      end
    end

    render json: {message: "ya son amigos"}
  end

  def getFriends
    @person =Person.find(params[:id])
    @result = []
    @person.friends.map do |item|
      @result<<item
    end
    Friendship.where(friend2: @person.id).map do |item|
       @result << Person.find(item.friend1)
    end
    puts 'type of result ' + @result.class.to_s
    render json: @result
  end

  private

  def set_event
    begin
      @event = Event.find(params[:event_id])
    rescue ActiveRecord::RecordNotFound
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def person_params
    params.permit(:name, :picture, :company_name, :description, :phone, :email, :city_id,:company_id, :title, :friend1_id, :friend2_id)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :set_profiles, only: [:new, :edit]
  before_action :set_event
  before_action :set_model, only: [:show, :edit]
  # GET /people
  # GET /people.json
  def index
    if @event != nil
      @people = @event.people.all
    else
      @people = Person.all
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    if @event != nil
      @person = @event.people.create(person_params)
      redirect_to = [@event, @person]
    else
      @person = Person.create(person_params)
      redirect_to = @person
    end

    respond_to do |format|
      if @person.valid?
        if @event != nil
          @person.persons_events.where(event_id: @event.id).take.update(profile_id: 2)
        end
        format.html { redirect_to redirect_to, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    redirect_to = @event != nil ? [@event, @place] : @place

    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    redirect_to = @event != nil ? [@event, :people] : people_url
    @person.destroy
    respond_to do |format|
      format.html { redirect_to redirect_to, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_model
    @model = @event == nil ? @person : [@event, @person]
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  def set_profiles
    @profiles = Profile.all
  end

  def set_event
    begin
      @event = Event.find(params[:event_id])
    rescue ActiveRecord::RecordNotFound
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:name, :picture, :description, :phone, :email, :city_id, :company_id, :title)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<% model= @event == nil ? person : [@event,person] %>
<%= form_with(model: model, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>
      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>
  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @model %> 
|
<% path= @event==nil ? people_path : event_people_path %>
<%= link_to 'Back', path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Description</th>
      <th>Phone</th>
      <th>Email</th>
      <th>City</th>
      <th>Company</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
    <% model= @event==nil ? person : [@event,person]  %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.picture %></td>
        <td><%= person.description %></td>
        <td><%= person.phone %></td>
        <td><%= person.email %></td>
        <td><%= person.city_id %></td>
        <td><%= person.company.name %></td>
        <td><%= person.title %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_polymorphic_path(model) %></td>
        <td><%= button_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% path= @event == nil ? new_person_path : new_event_person_path %>
<%= link_to 'New Person', path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<% path= @event == nil ? people_path : event_people_path %>
<%= link_to 'Back', path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @person.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @person.description %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @person.company.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @person.title %>
</p>


<% path= @event == nil ? people_path : event_people_path %>
<%= link_to 'Edit', edit_polymorphic_path(@model) %> |
<%= link_to 'Back', path %>