config/routes.rb
Rails.application.routes.draw do
  get '/version', to: 'events#getVersion'
  resources :faqs
  resources :places

  
  resources :multimedia_types
  resources :people
  resources :profiles
  resources :events
  resources :events do
    resources :places
    resources :activities
    resources :event_dates
    resources :people
    resources :information
    resources :multimedia
  end
  resources :companies
  namespace :api do
    namespace :v1 do
      resources :faqs
      resources :places

      
      resources :multimedia_types
      # resources :people
      resources :profiles
      resources :events
      resources :companies
      resources :events do
        resources :places
        resources :event_dates
        resources :activities
        resources :people
        resources :information
        resources :multimedia
        post '/message', to: 'events#postMessage'
      end
      post '/friendships', to: 'people#addFriend', as: 'new_friendship'
      get '/friendships/:id', to: 'people#getFriends'
      
    end
  end
  root to: "events#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activities_person.rb
class ActivitiesPerson < ApplicationRecord
  belongs_to :activity
  belongs_to :person
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :event_date
  belongs_to :places_event
  has_many :activities_people, dependent: :destroy
  has_many :people, through: :activities_people
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :person
  belongs_to :event_date
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :persons
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :persons_events, -> { where profile_id: 2 }
  has_many :people, -> { order(:name) }, through: :persons_events
  has_many :profiles, through: :persons_events
  has_many :multimedia
  has_many :information
  has_many :event_dates, -> { order(:date) }
  has_many :faqs
  has_many :places_events
  has_many :places, through: :places_events
  has_many :activities, through: :places_events
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  belongs_to :event
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :person, :foreign_key => :friend1
    belongs_to :person, :foreign_key => :friend2
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :event
end

app/models/multimedia_type.rb
class MultimediaType < ApplicationRecord
  has_many :multimedia
end

app/models/multimedium.rb
class Multimedium < ApplicationRecord
  belongs_to :multimedia_type
  belongs_to :event
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :company, optional: true
  has_many :persons_events, dependent: :destroy
  has_many :events, through: :persons_events
  has_many :profiles, through: :persons_events
  has_many :activities_people, dependent: :destroy
  has_many :activities, through: :activities_people
  has_many :friendships ,:foreign_key => :friend1
  has_many :friends, through: :friendships,source: :person
end

app/models/persons_event.rb
class PersonsEvent < ApplicationRecord
  belongs_to :person
  belongs_to :event
  # belongs_to :profile
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :places_events
  has_many :events, through: :places_events
  has_many :activities, through: :places_events
end

app/models/places_event.rb
class PlacesEvent < ApplicationRecord
  belongs_to :place
  belongs_to :event
  has_many :activities
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :persons_events
  has_many :events, through: :persons_events
  has_many :people, through: :persons_events
end

app/controllers/api/v1/places_controller.rb
class Api::V1::PlacesController < ApplicationController
  before_action :set_place, only: [:show, :update, :destroy]
  before_action :set_event
  # GET /places
  def index
    if @event != nil
      @places = @event.places.all
    else
      @places = Place.all
    end

    render json: @places
  end

  # GET /places/1
  def show
    render json: @place
  end

  # POST /places
  def create
    if @event != nil
      @place = @event.places().create(place_params)
    else
      @place = Place.create(place_params)
    end
    if @place.valid?
      render json: @place, status: :created, location: @place
    else
      render json: @place.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      render json: @place
    else
      render json: @place.errors, status: :unprocessable_entity
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end

  def set_event
    begin
      @event = Event.find(params[:event_id])
    rescue ActiveRecord::RecordNotFound
    end
  end

  # Only allow a trusted parameter "white list" through.
  def place_params
    params.require(:place).permit(:name, :address, :city_id)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :set_event
  # GET /places
  # GET /places.json
  def index
    if @event != nil
      @places = @event.places.all
    else
      @places = Place.all
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    if @event == nil
      @model = @place
    else
      @model = [@event, @place]
    end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
    if @event == nil
      @model = @place
    else
      @model = [@event, @place]
    end
  end

  # POST /places
  # POST /places.json
  def create
    if @event != nil
      @place = @event.places().create(place_params)
      redirect_to = [@event, @place]
    else
      @place = Place.create(place_params)
      redirect_to = @place
    end

    respond_to do |format|
      if @place.valid?
        format.html { redirect_to redirect_to, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    if @event != nil
      redirect_to = [@event, @place]
    else
      redirect_to = @place
    end
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to redirect_to, notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    redirect_to = @event != nil ? [@event, :places] : places_url

    @place.destroy
    respond_to do |format|
      format.html { redirect_to redirect_to, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end

  def set_event
    begin
      @event = Event.find(params[:event_id])
    rescue ActiveRecord::RecordNotFound
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def place_params
    params.require(:place).permit(:name, :address, :city_id)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/places/_form.html.erb
<%if @event==nil%>
    <%- model=place %>
<%else%>
    <%- model=[@event,place] %>
<%end%>


<%= form_with(model: model, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @model %> |
<% path= @event==nil ? places_path : event_places_path  %>
<%= link_to 'Back', path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Places</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <% model= @event==nil ? place : [@event,place]  %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.city_id %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_polymorphic_path(model)  %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% path= @event==nil ? new_place_path : new_event_place_path  %>
<%= link_to 'New Place', path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place ,event: @event %>
<%if @event==nil%>
    <%= link_to 'Back', places_path %>
<%else%>
    <%= link_to 'Back', event_places_path %>
<%end%>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>
<p>
  <strong>City:</strong>
  <%= @place.city_id %>
</p>
<%= link_to 'Edit', edit_polymorphic_path(@model) %> |
<% if @event==nil%>
<%= link_to 'Back', places_path %>
<%else%>
  <%= link_to 'Back', event_places_path %>
<%end%>